[package]
name = "sakemas-bot"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.68"
chrono = "0.4.34"
cron = "0.12.0"
poise = { version = "0.6.1", features = ["collector"] }
reqwest = "0.11.24"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.114"
shuttle-runtime = "0.39.0"
shuttle-secrets = "0.39.0"
shuttle-serenity = "0.39.0"
shuttle-shared-db = { version = "0.39.0", features = ["postgres", "sqlx"] }
sqlx = { version = "0.7.3", features = ["runtime-tokio", "macros"] }
tokio = { version = "1.26.0", features = ["full"] }
tracing = "0.1.37"
twitter-v2 = "0.1.8"
