[package]
name = "sakemas-bot"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.68"
chrono = "0.4.34"
cron = "0.12.0"
poise = "0.6.1"
shuttle-runtime = "0.39.0"
shuttle-secrets = "0.39.0"
shuttle-serenity = "0.39.0"
tracing = "0.1.37"
tokio = { version = "1.26.0", features = ["full"] }
