[package]
name = "sakemas-bot"
version = "0.0.3"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.86"
async-recursion = "1.1.1"
chrono = "0.4.38"
cron = "0.12.0"
nestify = "0.3.3"
poise = { version = "0.6.1", features = ["collector"] }
reqwest = { version = "0.12.4", features = ["multipart"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
shuttle-runtime = "0.45.0"
shuttle-serenity = "0.45.0"
shuttle-shared-db = { version = "0.45.0", features = ["postgres", "sqlx"] }
sqlx = { version = "0.7.4", features = ["runtime-tokio", "macros"] }
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["full"] }
tracing = "0.1.37"
twapi-v2 = "0.15.0"
twitter-text = "0.2.0"
twitter_text_config = "0.2.0"
twitter-v2 = "0.1.8"
