[package]
name = "sakemas-bot"
version = "0.0.4"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
chrono = "0.4"
cron = "0.12"
nestify = "0.3"
poise = { version = "0.6.1", features = ["collector"] }
reqwest = { version = "0.12.10", features = ["multipart"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shuttle-runtime = "0.49"
shuttle-serenity = "0.49"
shuttle-shared-db = { version = "0.49", features = ["postgres", "sqlx"] }
sqlx = { version = "0.8.2", features = ["runtime-tokio", "macros"] }
thiserror = "1.0"
tokio = { version = "1.42", features = ["full"] }
tracing = "0.1.41"
twapi-v2 = { version = "0.15.2", features = ["upload"] }
twitter-text = "0.2.0"
twitter_text_config = "0.2.0"
