name: Shuttle Deploy

on:
  push:
    branches: ["main"]
  pull_request_target:
    types: [closed]
    branches: ["main"]
  workflow_dispatch:

jobs:
  security-check:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    outputs:
      approved: ${{ steps.check.outputs.approved }}
    steps:
      - name: Check if PR was approved before merge
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            if (!context.payload.pull_request.merged) {
              core.setOutput('approved', 'false');
              return;
            }

            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const approvedReviews = reviews.filter(review =>
              review.state === 'APPROVED' &&
              review.user.type !== 'Bot'
            );

            core.setOutput('approved', approvedReviews.length > 0 ? 'true' : 'false');

  deploy:
    runs-on: ubuntu-latest
    needs: [security-check]
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request_target' &&
       needs.security-check.outputs.approved == 'true') ||
      github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.merge_commit_sha || github.sha }}

      - uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: proj_01K183SSVHDZD7SYM3DZPT30Z7
          secrets: |
            DISCORD_TOKEN = '${{ secrets.DISCORD_TOKEN }}'
            TWITTER_CLIENT_ID = '${{ secrets.TWITTER_CLIENT_ID }}'
            TWITTER_CLIENT_SECRET = '${{ secrets.TWITTER_CLIENT_SECRET }}'
            VC_ANNOUNCEMENT_CHANNEL = '${{ secrets.VC_ANNOUNCEMENT_CHANNEL }}'
            WELCOME_CHANNEL = '${{ secrets.WELCOME_CHANNEL }}'
            CAUTION_CHANNEL = '${{ secrets.CAUTION_CHANNEL }}'
            INTRODUCTION_CHANNEL = '${{ secrets.INTRODUCTION_CHANNEL }}'
            X_POSTER_CHANNEL = '${{ secrets.X_POSTER_CHANNEL }}'
