name: Shuttle Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: proj_01K183SSVHDZD7SYM3DZPT30Z7
          secrets: |
            DISCORD_TOKEN = '${{ secrets.DISCORD_TOKEN }}'
            TWITTER_CLIENT_ID = '${{ secrets.TWITTER_CLIENT_ID }}'
            TWITTER_CLIENT_SECRET = '${{ secrets.TWITTER_CLIENT_SECRET }}'
            VC_ANNOUNCEMENT_CHANNEL = '${{ secrets.VC_ANNOUNCEMENT_CHANNEL }}'
            WELCOME_CHANNEL = '${{ secrets.WELCOME_CHANNEL }}'
            CAUTION_CHANNEL = '${{ secrets.CAUTION_CHANNEL }}'
            INTRODUCTION_CHANNEL = '${{ secrets.INTRODUCTION_CHANNEL }}'
            X_POSTER_CHANNEL = '${{ secrets.X_POSTER_CHANNEL }}'
