name: Shuttle Deploy

on:
  push:
    branches: ["main"]
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    # 承認されたレビューまたはmainブランチへのpushの場合のみ実行
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request_review' &&
       github.event.review.state == 'approved' &&
       github.event.pull_request.base.ref == 'main') ||
      github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # PRレビューの場合はPRのHEADをチェックアウト、それ以外はデフォルト
          ref: ${{ github.event_name == 'pull_request_review' && github.event.pull_request.head.sha || github.sha }}

      - name: Deploy info
        run: |
          echo "Event: ${{ github.event_name }}"
          if [ "${{ github.event_name }}" = "pull_request_review" ]; then
            echo "PR #${{ github.event.pull_request.number }} approved by ${{ github.event.review.user.login }}"
            echo "Deploying PR changes..."
          elif [ "${{ github.event_name }}" = "push" ]; then
            echo "Deploying main branch changes..."
          else
            echo "Manual deployment triggered"
          fi

      - uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: proj_01K183SSVHDZD7SYM3DZPT30Z7
          secrets: |
            DISCORD_TOKEN = '${{ secrets.DISCORD_TOKEN }}'
            TWITTER_CLIENT_ID = '${{ secrets.TWITTER_CLIENT_ID }}'
            TWITTER_CLIENT_SECRET = '${{ secrets.TWITTER_CLIENT_SECRET }}'
            VC_ANNOUNCEMENT_CHANNEL = '${{ secrets.VC_ANNOUNCEMENT_CHANNEL }}'
            WELCOME_CHANNEL = '${{ secrets.WELCOME_CHANNEL }}'
            CAUTION_CHANNEL = '${{ secrets.CAUTION_CHANNEL }}'
            INTRODUCTION_CHANNEL = '${{ secrets.INTRODUCTION_CHANNEL }}'
            X_POSTER_CHANNEL = '${{ secrets.X_POSTER_CHANNEL }}'
